version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"

  app1:
    build: ./server
    container_name: express-app1
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_NAME=Server1

  app2:
    build: ./server
    container_name: express-app2
    restart: always
    ports:
      - "3002:3000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SERVER_NAME=Server2
